// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgl9xJnIDVHm-SqFGpiHbHJBzTFRdr0Vs',
    appId: '1:874603911408:web:38e812f4c8c06caaf40a35',
    messagingSenderId: '874603911408',
    projectId: 'cicd-test-f947d',
    authDomain: 'cicd-test-f947d.firebaseapp.com',
    storageBucket: 'cicd-test-f947d.firebasestorage.app',
    measurementId: 'G-V4TQ1QZLDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFwRzpqKJ7Y_dmPWJ0qeMnrAy6Aq2lHVs',
    appId: '1:874603911408:android:a8cf9bf98a92e282f40a35',
    messagingSenderId: '874603911408',
    projectId: 'cicd-test-f947d',
    storageBucket: 'cicd-test-f947d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbioRhOdfFjHZLo0tH9-Cg6DW60e1GLhQ',
    appId: '1:874603911408:ios:32e9539124100eadf40a35',
    messagingSenderId: '874603911408',
    projectId: 'cicd-test-f947d',
    storageBucket: 'cicd-test-f947d.firebasestorage.app',
    iosBundleId: 'com.example.changisha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbioRhOdfFjHZLo0tH9-Cg6DW60e1GLhQ',
    appId: '1:874603911408:ios:32e9539124100eadf40a35',
    messagingSenderId: '874603911408',
    projectId: 'cicd-test-f947d',
    storageBucket: 'cicd-test-f947d.firebasestorage.app',
    iosBundleId: 'com.example.changisha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgl9xJnIDVHm-SqFGpiHbHJBzTFRdr0Vs',
    appId: '1:874603911408:web:a40f7768f0e8548df40a35',
    messagingSenderId: '874603911408',
    projectId: 'cicd-test-f947d',
    authDomain: 'cicd-test-f947d.firebaseapp.com',
    storageBucket: 'cicd-test-f947d.firebasestorage.app',
    measurementId: 'G-CT721HJX9K',
  );
}
